# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  runningEnv = ENV["RUNNING_ENV"]

  if runningEnv == "local"
    puts "Running locally.."
    config.vm.provider "virtualbox"
    config.vm.define "appserver-local" do |appserver|
      appserver.vm.box = 'ubuntu/bionic64'
      appserver.vm.provision 'shell', :inline => <<-SHELL    
      source /etc/lsb-release
      wget https://apt.puppetlabs.com/puppet7-release-${DISTRIB_CODENAME}.deb
      dpkg -i puppet7-release-${DISTRIB_CODENAME}.deb
      apt-get update
      systemctl start puppetserver
      apt-get -y install puppet-agent
      SHELL
      appserver.vm.provision 'puppet' do |pup|
        pup.manifests_path = "./manifests"
        pup.manifest_file = 'appserver.pp'
      end
    end

    config.vm.define "dbserver-local" do |dbserver|
      dbserver.vm.box = 'ubuntu/bionic64'
      dbserver.vm.provision 'shell', :inline => <<-SHELL
      source /etc/lsb-release
      wget https://apt.puppetlabs.com/puppet7-release-${DISTRIB_CODENAME}.deb
      dpkg -i puppet7-release-${DISTRIB_CODENAME}.deb
      apt-get update
      systemctl start puppetserver
      apt-get -y install puppet-agent
      /opt/puppetlabs/bin/puppet module install puppetlabs-mysql --version 12.0.1
      SHELL
      dbserver.vm.provision 'puppet' do |pup|
        pup.manifests_path = "./manifests"
        pup.manifest_file = 'dbserver.pp'
      end
    end
  
  elsif runningEnv == "cloud"
    puts "Running on the cloud.."
    config.vm.hostname = 'vagrant-test'
    config.vm.synced_folder ".", "/vagrant", type: "rsync"
    config.puppet_install.puppet_version = '6.24.0'
    config.vm.provider :digital_ocean do |provider, override|
      override.ssh.private_key_path = '~/.ssh/id_rsa'
      override.vm.box = 'digital_ocean'
      override.vm.box_url = "https://github.com/devopsgroup-io/vagrant-digitalocean/raw/master/box/digital_ocean.box"
      override.vm.allowed_synced_folder_types = :rsync
      provider.token = ENV['DIGITALOCEAN_TOKEN']  
      provider.image = 'ubuntu-18-04-x64'
      provider.region = 'nyc1'
      provider.size = 's-1vcpu-1gb'
      provider.setup = false
    end  
    config.vm.define "appserver" do |appserver|
      appserver.vm.box = 'digital_ocean'
      appserver.puppet_install.puppet_version = '6.24.0'
      appserver.vm.provision 'puppet' do |pup|
        pup.manifests_path = "./manifests"
        pup.manifest_file = 'appserver.pp'
      end
    end
    config.vm.define "dbserver" do |dbserver|
      dbserver.vm.box = 'digital_ocean'
      dbserver.puppet_install.puppet_version = '6.24.0'
      dbserver.vm.provision 'shell', :inline => <<-SHELL
      /opt/puppetlabs/bin/puppet module install puppetlabs-mysql --version 8.0.0
      SHELL
      dbserver.vm.provision 'puppet' do |pup|
        pup.manifests_path = "./manifests"
        pup.manifest_file = 'dbserver.pp'
      end
    end
  
  end
  
end
